clc; 
close all; 
k = input("Enter the number of bits k:"); 
n = input("Enter the code length n:"); 
m = (n-k); 
disp("m="); 
disp(m); 
p=input("enter parity matrix:"); 
disp("p ="); 
disp(p); 
Pt = transpose(p); 
disp("Transpose of Matrix Pt:"); 
disp(Pt); 
I=eye(k); 
disp("I:"); 
disp(I); 
G=cat(2,I,p); 
disp("G:"); 
disp(G); 
c2=0; 
for mw=0:((2^k)-1) 
msg=dec2bin(mw,k); 
disp("msg:"); 
disp(msg); 
c1=msg*G;
disp(c1); 
c2=rem(c1,2); 
disp(c2); 
end 
c6=0;c5=0; 
for i=1:((2^k)-1) 
c3 = dec2bin(i,k); 
c6 = c3*G; 
disp(c6); 
c1 = rem(c6,2); 
dmin = n; 
for j=1:((2^k)-1) 
c4 = dec2bin(j,k); 
c5 = c4*G; 
c2 = rem(c5,2); 
x = xor(c1,c2); 
s = sum(x); 
r1(i,j) = s; 
if(s~=0) 
if(s<dmin) 
dmin = s; 
end; 
end; 
end; 
end; 
t = dmin - 1; 
disp("Error detection capability:"); disp(t); 
e=(t/2); 
disp("Error correction"); 
disp(e); 
r=input("Enter received code:"); I=eye(m); 
H=[Pt I]; 
disp(H); 
Ht=transpose(H); 
disp("Ht:");
E = eye(n); 
E1 = E*Ht; 
disp("Syndrome table:"); 
disp("E1"); 
disp(E1); 
s1 = r*Ht; 
s2 = rem(s1,2); 
disp("Syndrome table for received code word:"); 
disp("s2:"); 
disp(s2); 
for i=1:n; 
if s2==E1(i,:); 
break; 
end; 
end; 
p1 = E(i,:); 
disp("p1:"); 
disp(p1); 
q = xor(r,p1); 
disp("Corrected code:"); 
disp(q); 